/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef AHROOBE_H
#define AHROOBE_H

/* function declarations */
void init_ahroobe(void);

#endif /* AHROOBE_H */
