/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ahroobe.h"

/*
 * The variables we want to tie the relevant OIDs to.
 * The agent will handle all GET and (if applicable) SET requests
 * to these variables automatically, changing the values as needed.
 */

long    refriMachCode = 3512435;  /* XXX: set default value */
long    refriNowTempL = 0;  /* XXX: set default value */
long    refriNowTempR = -10;  /* XXX: set default value */
u_long    refriDoorOpen = 0;  /* XXX: set default value */
long    refriKg = 150;  /* XXX: set default value */
long    airconMachCode = 7590;  /* XXX: set default value */
long    airconHopeTemp = 18;  /* XXX: set default value */
long    airconNowTemp = 30;  /* XXX: set default value */
u_long    airconDura = 0;  /* XXX: set default value */
long    airconOn = 0;  /* XXX: set default value */
long    printerMachCode = 77777;  /* XXX: set default value */
long    printerRemInk = 0;  /* XXX: set default value */
long    printerOn = 0;  /* XXX: set default value */
long    printerPaper = 0;  /* XXX: set default value */
long    printerLog = 4;  /* XXX: set default value */
long    washmachCode = 6016;  /* XXX: set default value */
long    washmachRemDet = 0;  /* XXX: set default value */
u_long    washmachDura = 0;  /* XXX: set default value */
long    washmachpower = 1200;  /* XXX: set default value */
long    washmachOn = 0;  /* XXX: set default value */
long    lightMachCode = 8421;  /* XXX: set default value */
long    lightconMaxBright = 400;  /* XXX: set default value */
long    lightconPower = 180;  /* XXX: set default value */
u_long    lightconDura = 0;  /* XXX: set default value */
long    lightconOn = 0;  /* XXX: set default value */

/*
 * Our initialization routine, called automatically by the agent 
 * (Note that the function name must match init_FILENAME()) 
 */
void
init_ahroobe(void)
{
  netsnmp_handler_registration *reg;

    const oid refriMachCode_oid[] = { 1,3,6,1,4,2,1,1 };
  static netsnmp_watcher_info refriMachCode_winfo;
    const oid refriNowTempL_oid[] = { 1,3,6,1,4,2,1,2 };
  static netsnmp_watcher_info refriNowTempL_winfo;
    const oid refriNowTempR_oid[] = { 1,3,6,1,4,2,1,3 };
  static netsnmp_watcher_info refriNowTempR_winfo;
    const oid refriDoorOpen_oid[] = { 1,3,6,1,4,2,1,4 };
  static netsnmp_watcher_info refriDoorOpen_winfo;
    const oid refriKg_oid[] = { 1,3,6,1,4,2,1,5 };
  static netsnmp_watcher_info refriKg_winfo;
    const oid airconMachCode_oid[] = { 1,3,6,1,4,2,2,1 };
  static netsnmp_watcher_info airconMachCode_winfo;
    const oid airconHopeTemp_oid[] = { 1,3,6,1,4,2,2,2 };
  static netsnmp_watcher_info airconHopeTemp_winfo;
    const oid airconNowTemp_oid[] = { 1,3,6,1,4,2,2,3 };
  static netsnmp_watcher_info airconNowTemp_winfo;
    const oid airconDura_oid[] = { 1,3,6,1,4,2,2,4 };
  static netsnmp_watcher_info airconDura_winfo;
    const oid airconOn_oid[] = { 1,3,6,1,4,2,2,5 };
  static netsnmp_watcher_info airconOn_winfo;
    const oid printerMachCode_oid[] = { 1,3,6,1,4,2,3,1 };
  static netsnmp_watcher_info printerMachCode_winfo;
    const oid printerRemInk_oid[] = { 1,3,6,1,4,2,3,2 };
  static netsnmp_watcher_info printerRemInk_winfo;
    const oid printerOn_oid[] = { 1,3,6,1,4,2,3,3 };
  static netsnmp_watcher_info printerOn_winfo;
    const oid printerPaper_oid[] = { 1,3,6,1,4,2,3,4 };
  static netsnmp_watcher_info printerPaper_winfo;
    const oid printerLog_oid[] = { 1,3,6,1,4,2,3,5 };
  static netsnmp_watcher_info printerLog_winfo;
    const oid washmachCode_oid[] = { 1,3,6,1,4,2,4,1 };
  static netsnmp_watcher_info washmachCode_winfo;
    const oid washmachRemDet_oid[] = { 1,3,6,1,4,2,4,2 };
  static netsnmp_watcher_info washmachRemDet_winfo;
    const oid washmachDura_oid[] = { 1,3,6,1,4,2,4,3 };
  static netsnmp_watcher_info washmachDura_winfo;
    const oid washmachpower_oid[] = { 1,3,6,1,4,2,4,4 };
  static netsnmp_watcher_info washmachpower_winfo;
    const oid washmachOn_oid[] = { 1,3,6,1,4,2,4,5 };
  static netsnmp_watcher_info washmachOn_winfo;
    const oid lightMachCode_oid[] = { 1,3,6,1,4,2,5,1 };
  static netsnmp_watcher_info lightMachCode_winfo;
    const oid lightconMaxBright_oid[] = { 1,3,6,1,4,2,5,2 };
  static netsnmp_watcher_info lightconMaxBright_winfo;
    const oid lightconPower_oid[] = { 1,3,6,1,4,2,5,3 };
  static netsnmp_watcher_info lightconPower_winfo;
    const oid lightconDura_oid[] = { 1,3,6,1,4,2,5,4 };
  static netsnmp_watcher_info lightconDura_winfo;
    const oid lightconOn_oid[] = { 1,3,6,1,4,2,5,5 };
  static netsnmp_watcher_info lightconOn_winfo;

  /*
   * a debugging statement.  Run the agent with -Dahroobe to see
   * the output of this debugging statement. 
   */
  DEBUGMSGTL(("ahroobe", "Initializing the ahroobe module\n"));


    /*
     * Register scalar watchers for each of the MIB objects.
     * The ASN type and RO/RW status are taken from the MIB definition,
     * but can be adjusted if needed.
     *
     * In most circumstances, the scalar watcher will handle all
     * of the necessary processing.  But the NULL parameter in the
     * netsnmp_create_handler_registration() call can be used to
     * supply a user-provided handler if necessary.
     *
     * This approach can also be used to handle Counter64, string-
     * and OID-based watched scalars (although variable-sized writeable
     * objects will need some more specialised initialisation).
     */
    DEBUGMSGTL(("ahroobe",
                "Initializing refriMachCode scalar integer.  Default value = %d\n",
                refriMachCode));
    reg = netsnmp_create_handler_registration(
             "refriMachCode", NULL,
              refriMachCode_oid, OID_LENGTH(refriMachCode_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&refriMachCode_winfo, &refriMachCode, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &refriMachCode_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched refriMachCode" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing refriNowTempL scalar integer.  Default value = %d\n",
                refriNowTempL));
    reg = netsnmp_create_handler_registration(
             "refriNowTempL", NULL,
              refriNowTempL_oid, OID_LENGTH(refriNowTempL_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&refriNowTempL_winfo, &refriNowTempL, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &refriNowTempL_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched refriNowTempL" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing refriNowTempR scalar integer.  Default value = %d\n",
                refriNowTempR));
    reg = netsnmp_create_handler_registration(
             "refriNowTempR", NULL,
              refriNowTempR_oid, OID_LENGTH(refriNowTempR_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&refriNowTempR_winfo, &refriNowTempR, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &refriNowTempR_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched refriNowTempR" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing refriDoorOpen scalar integer.  Default value = %d\n",
                refriDoorOpen));
    reg = netsnmp_create_handler_registration(
             "refriDoorOpen", NULL,
              refriDoorOpen_oid, OID_LENGTH(refriDoorOpen_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&refriDoorOpen_winfo, &refriDoorOpen, sizeof(u_long),
			      ASN_COUNTER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &refriDoorOpen_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched refriDoorOpen" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing refriKg scalar integer.  Default value = %d\n",
                refriKg));
    reg = netsnmp_create_handler_registration(
             "refriKg", NULL,
              refriKg_oid, OID_LENGTH(refriKg_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&refriKg_winfo, &refriKg, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &refriKg_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched refriKg" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing airconMachCode scalar integer.  Default value = %d\n",
                airconMachCode));
    reg = netsnmp_create_handler_registration(
             "airconMachCode", NULL,
              airconMachCode_oid, OID_LENGTH(airconMachCode_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&airconMachCode_winfo, &airconMachCode, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &airconMachCode_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched airconMachCode" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing airconHopeTemp scalar integer.  Default value = %d\n",
                airconHopeTemp));
    reg = netsnmp_create_handler_registration(
             "airconHopeTemp", NULL,
              airconHopeTemp_oid, OID_LENGTH(airconHopeTemp_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&airconHopeTemp_winfo, &airconHopeTemp, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &airconHopeTemp_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched airconHopeTemp" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing airconNowTemp scalar integer.  Default value = %d\n",
                airconNowTemp));
    reg = netsnmp_create_handler_registration(
             "airconNowTemp", NULL,
              airconNowTemp_oid, OID_LENGTH(airconNowTemp_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&airconNowTemp_winfo, &airconNowTemp, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &airconNowTemp_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched airconNowTemp" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing airconDura scalar integer.  Default value = %d\n",
                airconDura));
    reg = netsnmp_create_handler_registration(
             "airconDura", NULL,
              airconDura_oid, OID_LENGTH(airconDura_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&airconDura_winfo, &airconDura, sizeof(u_long),
			      ASN_COUNTER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &airconDura_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched airconDura" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing airconOn scalar integer.  Default value = %d\n",
                airconOn));
    reg = netsnmp_create_handler_registration(
             "airconOn", NULL,
              airconOn_oid, OID_LENGTH(airconOn_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&airconOn_winfo, &airconOn, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &airconOn_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched airconOn" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing printerMachCode scalar integer.  Default value = %d\n",
                printerMachCode));
    reg = netsnmp_create_handler_registration(
             "printerMachCode", NULL,
              printerMachCode_oid, OID_LENGTH(printerMachCode_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&printerMachCode_winfo, &printerMachCode, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &printerMachCode_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched printerMachCode" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing printerRemInk scalar integer.  Default value = %d\n",
                printerRemInk));
    reg = netsnmp_create_handler_registration(
             "printerRemInk", NULL,
              printerRemInk_oid, OID_LENGTH(printerRemInk_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&printerRemInk_winfo, &printerRemInk, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &printerRemInk_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched printerRemInk" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing printerOn scalar integer.  Default value = %d\n",
                printerOn));
    reg = netsnmp_create_handler_registration(
             "printerOn", NULL,
              printerOn_oid, OID_LENGTH(printerOn_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&printerOn_winfo, &printerOn, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &printerOn_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched printerOn" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing printerPaper scalar integer.  Default value = %d\n",
                printerPaper));
    reg = netsnmp_create_handler_registration(
             "printerPaper", NULL,
              printerPaper_oid, OID_LENGTH(printerPaper_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&printerPaper_winfo, &printerPaper, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &printerPaper_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched printerPaper" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing printerLog scalar integer.  Default value = %d\n",
                printerLog));
    reg = netsnmp_create_handler_registration(
             "printerLog", NULL,
              printerLog_oid, OID_LENGTH(printerLog_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&printerLog_winfo, &printerLog, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &printerLog_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched printerLog" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing washmachCode scalar integer.  Default value = %d\n",
                washmachCode));
    reg = netsnmp_create_handler_registration(
             "washmachCode", NULL,
              washmachCode_oid, OID_LENGTH(washmachCode_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&washmachCode_winfo, &washmachCode, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &washmachCode_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched washmachCode" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing washmachRemDet scalar integer.  Default value = %d\n",
                washmachRemDet));
    reg = netsnmp_create_handler_registration(
             "washmachRemDet", NULL,
              washmachRemDet_oid, OID_LENGTH(washmachRemDet_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&washmachRemDet_winfo, &washmachRemDet, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &washmachRemDet_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched washmachRemDet" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing washmachDura scalar integer.  Default value = %d\n",
                washmachDura));
    reg = netsnmp_create_handler_registration(
             "washmachDura", NULL,
              washmachDura_oid, OID_LENGTH(washmachDura_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&washmachDura_winfo, &washmachDura, sizeof(u_long),
			      ASN_COUNTER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &washmachDura_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched washmachDura" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing washmachpower scalar integer.  Default value = %d\n",
                washmachpower));
    reg = netsnmp_create_handler_registration(
             "washmachpower", NULL,
              washmachpower_oid, OID_LENGTH(washmachpower_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&washmachpower_winfo, &washmachpower, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &washmachpower_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched washmachpower" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing washmachOn scalar integer.  Default value = %d\n",
                washmachOn));
    reg = netsnmp_create_handler_registration(
             "washmachOn", NULL,
              washmachOn_oid, OID_LENGTH(washmachOn_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&washmachOn_winfo, &washmachOn, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &washmachOn_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched washmachOn" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing lightMachCode scalar integer.  Default value = %d\n",
                lightMachCode));
    reg = netsnmp_create_handler_registration(
             "lightMachCode", NULL,
              lightMachCode_oid, OID_LENGTH(lightMachCode_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&lightMachCode_winfo, &lightMachCode, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &lightMachCode_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched lightMachCode" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing lightconMaxBright scalar integer.  Default value = %d\n",
                lightconMaxBright));
    reg = netsnmp_create_handler_registration(
             "lightconMaxBright", NULL,
              lightconMaxBright_oid, OID_LENGTH(lightconMaxBright_oid),
              HANDLER_CAN_RONLY);
    netsnmp_init_watcher_info(&lightconMaxBright_winfo, &lightconMaxBright, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &lightconMaxBright_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched lightconMaxBright" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing lightconPower scalar integer.  Default value = %d\n",
                lightconPower));
    reg = netsnmp_create_handler_registration(
             "lightconPower", NULL,
              lightconPower_oid, OID_LENGTH(lightconPower_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&lightconPower_winfo, &lightconPower, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &lightconPower_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched lightconPower" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing lightconDura scalar integer.  Default value = %d\n",
                lightconDura));
    reg = netsnmp_create_handler_registration(
             "lightconDura", NULL,
              lightconDura_oid, OID_LENGTH(lightconDura_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&lightconDura_winfo, &lightconDura, sizeof(u_long),
			      ASN_COUNTER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &lightconDura_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched lightconDura" );
    }

    DEBUGMSGTL(("ahroobe",
                "Initializing lightconOn scalar integer.  Default value = %d\n",
                lightconOn));
    reg = netsnmp_create_handler_registration(
             "lightconOn", NULL,
              lightconOn_oid, OID_LENGTH(lightconOn_oid),
              HANDLER_CAN_RWRITE);
    netsnmp_init_watcher_info(&lightconOn_winfo, &lightconOn, sizeof(long),
			      ASN_INTEGER, WATCHER_FIXED_SIZE);
if (netsnmp_register_watched_scalar( reg, &lightconOn_winfo ) < 0 ) {
        snmp_log( LOG_ERR, "Failed to register watched lightconOn" );
    }


  DEBUGMSGTL(("ahroobe",
              "Done initalizing ahroobe module\n"));
}
